// <auto-generated />
using System;
using LD.Messaging.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LD.Messaging.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockRecordsDbContext))]
    [Migration("20260517000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingestion")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LD.Messaging.Infrastructure.Persistence.Entities.StockRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric");

                    b.Property<decimal>("Close")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("High")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Open")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("RecordTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("idx_stock_records_created");

                    b.HasIndex("Exchange")
                        .HasDatabaseName("idx_stock_records_exchange");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_stock_records_symbol");

                    b.HasIndex("RecordDate", "Exchange")
                        .HasDatabaseName("idx_stock_records_date_exchange");

                    b.ToTable("stock_records", "ingestion");

                    b.HasComment("Stock market data records ingested from Kafka");
                });
#pragma warning restore 612, 618
        }
    }
}

